# coding: utf-8

"""
    Grocery List Management API

    A simple REST API for managing a grocery shopping list, designed for student term projects.

    The version of the OpenAPI document: 1.0.0
    Contact: support@example.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.grocery_items_api import router as GroceryItemsApiRouter

app = FastAPI(
    title="Grocery List Management API",
    description="A simple REST API for managing a grocery shopping list, designed for student term projects.",
    version="1.0.0",
)

app.include_router(GroceryItemsApiRouter)
